import "./globals.css";
import { Inter } from "next/font/google";
import NotificationFactoryProvider from "../components/notification-factory/NotificationFactoryProvider";
import NotificationFactory from "../components/notification-factory/NotificationFactory";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationFactoryProvider>
          <NotificationFactory />
          {children}
        </NotificationFactoryProvider>
      </body>
    </html>
  );
}
